/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    input usb_rx,
    output reg usb_tx,
    output reg [7:0] led,
    input [23:0] io_dip,
    input [4:0] io_button,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    output reg [23:0] io_led
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [8-1:0] M_manual_tester_io_seg;
  wire [4-1:0] M_manual_tester_io_sel;
  wire [24-1:0] M_manual_tester_io_led;
  reg [1-1:0] M_manual_tester_clk;
  reg [1-1:0] M_manual_tester_rst;
  reg [24-1:0] M_manual_tester_io_dip;
  reg [5-1:0] M_manual_tester_io_button;
  manual_alu_tester_2 manual_tester (
    .clk(M_manual_tester_clk),
    .rst(M_manual_tester_rst),
    .io_dip(M_manual_tester_io_dip),
    .io_button(M_manual_tester_io_button),
    .io_seg(M_manual_tester_io_seg),
    .io_sel(M_manual_tester_io_sel),
    .io_led(M_manual_tester_io_led)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    usb_tx = usb_rx;
    io_led = 24'h000000;
    io_seg = 8'h00;
    io_sel = 4'h0;
    M_manual_tester_io_dip = io_dip;
    M_manual_tester_io_button = io_button;
    M_manual_tester_clk = clk;
    M_manual_tester_rst = rst;
    io_led = 24'h000000;
    io_seg = M_manual_tester_io_seg;
    io_sel = M_manual_tester_io_sel;
    io_led = M_manual_tester_io_led;
  end
endmodule
