/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checker_2 (
    input sum1,
    input cout1,
    input sum2,
    input cout2,
    output reg out
  );
  
  
  
  always @* begin
    if (sum1 == sum2 && cout1 == cout2) begin
      out = 1'h1;
    end else begin
      out = 1'h0;
    end
  end
endmodule
